"""add key to think tanks

Revision ID: 13b61c27a102
Revises: 7118113c30b6
Create Date: 2026-07-17 17:42:51.444130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b61c27a102'
down_revision: Union[str, Sequence[str], None] = '7118113c30b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "think_tanks",
        sa.Column("key", sa.String(length=100), nullable=True),
    )

    key_by_id = {
        1: "brookings",
        2: "heritage",
        3: "cfr",
        4: "cato",
        5: "csis",
        6: "aei",
        7: "rand",
        8: "carnegie",
        9: "atlantic_council",
        10: "hoover",
        11: "piie",
        12: "wilson",
        13: "cap",
        14: "nber",
        15: "bruegel",
        16: "chatham_house",
        17: "cepr",
        18: "ifri",
        19: "swp",
        20: "dgap",
        21: "ecfr",
        22: "iiss",
        23: "sipri",
        24: "jiia",
        25: "rieti",
        26: "eria",
        27: "kdi",
        28: "kiep",
        29: "siis",
        30: "cicir",
        31: "leibniz",
        32: "max_planck",
        33: "helmholtz",
        34: "fraunhofer",
        35: "ifo",
        36: "ifw_kiel",
        37: "diw",
        38: "rwi",
        39: "iwh",
        40: "wzb",
        41: "giga",
        42: "mpi_ic",
        43: "fraunhofer_isi",
        44: "fraunhofer_imw",
        45: "fraunhofer_sit",
    }

    for think_tank_id, think_tank_key in key_by_id.items():
        op.execute(
            sa.text(
                "UPDATE think_tanks "
                "SET key = :think_tank_key "
                "WHERE id = :think_tank_id"
            ).bindparams(
                think_tank_id=think_tank_id,
                think_tank_key=think_tank_key,
            )
        )

    op.alter_column(
        "think_tanks",
        "key",
        existing_type=sa.String(length=100),
        nullable=False,
    )
    op.create_index(
        op.f("ix_think_tanks_key"),
        "think_tanks",
        ["key"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_think_tanks_key'), table_name='think_tanks')
    op.drop_column('think_tanks', 'key')
    # ### end Alembic commands ###
