"""add report ai chunks

Revision ID: cc55b8fca9a8
Revises: f2d4c1a9b8e7
Create Date: 2026-09-06 21:16:44.061404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc55b8fca9a8'
down_revision: Union[str, Sequence[str], None] = 'f2d4c1a9b8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_ai_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=30), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('source_start', sa.Integer(), nullable=False),
    sa.Column('source_end', sa.Integer(), nullable=False),
    sa.Column('report_content_hash', sa.String(length=64), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'chunk_type', 'chunk_index', name='uq_report_ai_chunk')
    )
    op.create_index('ix_report_ai_chunks_report_status', 'report_ai_chunks', ['report_id', 'status'], unique=False)
    op.create_index(op.f('ix_report_ai_chunks_status'), 'report_ai_chunks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_ai_chunks_status'), table_name='report_ai_chunks')
    op.drop_index('ix_report_ai_chunks_report_status', table_name='report_ai_chunks')
    op.drop_table('report_ai_chunks')
    # ### end Alembic commands ###
