"""add ai fields

Revision ID: e038b9014347
Revises: c3b41e5cfbd4
Create Date: 2026-08-10 12:55:11.086031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e038b9014347'
down_revision: Union[str, Sequence[str], None] = 'c3b41e5cfbd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('reports', 'ai_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('reports', 'ai_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
